### ISSUE TITLE
Cultureland 모듈문제

### ISSUE THREAD

**Issue by scottjsh** [SKITO-AZ/Cultureland-API#1]
Cultureland 모듈은 무엇을 사용하나요?

**Comment by SKITO-AZ** [comment]
자체 개발 모듈을 이용 중이긴 합니다. 해당 프로젝트는 https://beta.diskiosk.xyz/docs의 API 서버의 작동 원리를 소스 코드로 공개함으로써 API 이용에 있어 안내 사항 외에 유저 데이터 수집을 안하는 것을 보여주기 위해 공개된 프로젝트입니다.
